---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "database.fullname" . }}-password
  labels:
    {{- include "database.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  password: {{ randAlphaNum 20 | b64enc | quote }}