---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "gateway.fullname" . }}-cr
  labels:
    rbac.example.com/aggregate-to-monitoring: "true"
    {{- include "gateway.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["nodes", "services", "endpoints", "pods", "deployments", "namespaces","componentstatuses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gateway.fullname" . }}-crb
roleRef:
  name: {{ include "gateway.fullname" . }}-cr
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
subjects:
  - kind: ServiceAccount
    name: {{ include "gateway.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}