{{- if .Values.aqua.token }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "enforcer.fullname" . }}-token
  labels:
    {{- include "enforcer.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.aqua.token | b64enc | quote }}
{{- end }}