{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "enforcer.serviceAccountName" . }}
  labels:
{{ include "enforcer.labels" . | nindent 4 }}
{{- end -}}
